spring.application.name=duckcore

# DataSource
spring.datasource.url=${URL_DATABASE:jdbc:postgresql://ep-rapid-hat-aiz9jklj-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${USER_DATABASE:neondb_owner}
spring.datasource.password=${PASS_DATABASE:npg_HKgn4R2esiUY}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true